### ISSUE TITLE
ldid problem on my mac?

### ISSUE THREAD

**Issue by amats211** [tihmstar/jbinit#2]
xcrun -sdk iphoneos clang -e__dyld_start -Wl,-dylinker -Wl,-dylinker_install_name,/usr/lib/dyld -nostdlib -static -Wl,-fatal_warnings -Wl,-dead_strip -Wl,-Z --target=arm64-apple-ios12.0 -std=gnu17 -flto -ffreestanding -U__nonnull -nostdlibinc -fno-stack-protector jbinit.c printf.c -o jbinit
mv jbinit com.apple.dyld
ldid -S com.apple.dyld
ldid.cpp(705): _assert(): Swap(mach_header_->filetype) == MH_EXECUTE || Swap(mach_header_->filetype) == MH_DYLIB || Swap(mach_header_->filetype) == MH_BUNDLE
make: *** [jbinit] Error 1

**Comment by snx14** [comment]
brew install ldid

**Comment by amats211** [comment]
thanks, it was indeed an outdated ldid version..
